### ISSUE TITLE
a Bug

### ISSUE THREAD

**Issue by shaobeichen** [IFmiss/react-website#1]

**Comment by shaobeichen** [comment]
Access to fetch at 'https://www.daiwei.site/php/server-php/article/index.php?name=getArticleLists' from origin 'https://daiwei.site' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by AnglerDW** [comment]
现在应该没有问题了吧
